version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: apt-get update; apt-get -y install emacs-nox ca-certificates plantuml
      - run:
          name: Generate
          command: emacs -Q --batch -l setup.el doc/Test.org -f org-html-export-to-html
      - store_artifacts:
          path: doc
