version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: apt-get update; apt-get -y install emacs-nox
      - run:
          name: Generate
          command: emacs -Q --batch --eval '(progn (find-file "doc/Test.org")(org-html-export-as-html))'
